# Hands on Numpy

## Importing numpy


In [2]:
import numpy as np


## Array initialization

In [3]:
array = np.array([1,2,3,4,5,6,7,8,9])

## Access Array

In [5]:
array[1]

np.int64(2)

In [6]:
array[8]

np.int64(9)

## Array attributes

In [7]:
array.ndim

1

In [8]:
array.shape

(9,)

In [9]:
array.size

9

In [10]:
array.dtype

dtype('int64')

## Basic array creation

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

## Adding,removing & sorting elements

In [22]:
np.sort([1,4,3])

array([1, 3, 4])

In [23]:
np.concatenate(([2,67,89],[3,4,5]))

array([ 2, 67, 89,  3,  4,  5])

## Reshape array

In [27]:
array = np.arange(6)
array

array([0, 1, 2, 3, 4, 5])

In [30]:
array.reshape(2,3,order="F")

array([[0, 2, 4],
       [1, 3, 5]])

## Convert 1D array into 2D array

In [33]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [34]:
array.shape

(5,)

In [35]:
array = array[np.newaxis,:]

In [36]:
array.shape

(1, 5)

In [37]:
array

array([[0, 1, 2, 3, 4]])

In [41]:
array = np.arange(5)
array = array[:,np.newaxis]
array

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [42]:
array.shape

(5, 1)

In [44]:
a = np.arange(5)
a.shape

(5,)

In [45]:
b = np.expand_dims(a,axis=1)

In [46]:
b.shape

(5, 1)

In [47]:
b = np.expand_dims(a,axis=0)

In [48]:
b.shape

(1, 5)

## Indexing and slicing

In [49]:
a = np.arange(5)

In [51]:
a[a<2]

array([0, 1])

In [59]:
a = np.array([[2,5,6,2],[3,6,7,2]])

In [60]:
a[a<5]

array([2, 2, 3, 2])

In [54]:
a[0:2]

array([[2, 5, 6, 2],
       [3, 6, 7, 2]])

In [55]:
a[0:1]

array([[2, 5, 6, 2]])

In [56]:
a[a%2==0]

array([2, 6, 2, 6, 2])

In [61]:
np.nonzero(a)

(array([0, 0, 0, 0, 1, 1, 1, 1]), array([0, 1, 2, 3, 0, 1, 2, 3]))

## Create array from existing data

In [66]:
a = np.arange(2,11,2)
b = np.arange(1,11,2)


In [67]:
np.vstack((a,b))

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [68]:
np.hstack((a,b))

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

## Array operation

In [69]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

In [70]:
a+b

array([ 2,  4,  6,  8, 10])

In [71]:
a * b

array([ 1,  4,  9, 16, 25])

In [72]:
a/b

array([1., 1., 1., 1., 1.])

In [73]:
a.sum()

np.int64(15)

In [81]:
c = np.array([[1,2],[3,4]])
c.sum(axis=1)

array([3, 7])

In [82]:
c.min()

np.int64(1)

In [83]:
c.max()

np.int64(4)

In [84]:
c[0,1]

np.int64(2)

In [85]:
c[0][1]

np.int64(2)

In [86]:
d  = np.array(([[3,4],[5,6]]))

In [87]:
c+d

array([[ 4,  6],
       [ 8, 10]])

In [88]:
c*d

array([[ 3,  8],
       [15, 24]])

In [92]:
e = np.array([[1,0],[0,1]])

In [93]:
e

array([[1, 0],
       [0, 1]])

In [95]:
f  = c*e

## Generating random numbers

In [99]:
rng = np.random.default_rng()

In [100]:
rng.random(3)

array([0.34640956, 0.82586985, 0.20530566])

In [101]:
rng.random((3,2))

array([[0.03598014, 0.33133195],
       [0.37550477, 0.36584214],
       [0.33482992, 0.1190997 ]])

In [104]:
rng.integers(6,size =(3,2))

array([[0, 1],
       [4, 5],
       [0, 3]])

In [105]:
np.unique(rng.integers(6,size =(3,2)))

array([0, 2, 4, 5])

## Transposing a matrix

In [106]:
a = np.array([[1,2,3],[4,5,6]])

In [107]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [108]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [109]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Reverse an array

In [114]:
np.flip(a)

array([[6, 5, 4],
       [3, 2, 1]])

In [115]:
np.flip(a[1])

array([6, 5, 4])

In [116]:
np.flip(a,axis=1)

array([[3, 2, 1],
       [6, 5, 4]])

In [117]:
np.flip(a,axis=0)

array([[4, 5, 6],
       [1, 2, 3]])

In [119]:
a[:,1]

array([2, 5])

## Reshaping & flatten array

In [120]:
a = np.array(([[1,2,3],[4,5,6]]))

In [123]:
b = a.flatten()

In [125]:
b.shape

(6,)

In [131]:
b[0] = 99

In [132]:
b

array([99,  2,  3,  4,  5,  6])

In [133]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
c = a.ravel()

In [135]:
c

array([1, 2, 3, 4, 5, 6])

In [136]:
c[0] = 99

In [137]:
c

array([99,  2,  3,  4,  5,  6])

In [138]:
a

array([[99,  2,  3],
       [ 4,  5,  6]])